### ISSUE TITLE
Alarm Silence

### ISSUE THREAD

**Issue by TC2013** [rnpenguin/cgm-remote-monitor#7] opened 2014-03-16 21:54 UTC
It would be great to have an option to silence the audible alarms for a specified number of minutes.

**Comment by ldesboro** [comment] 2014-03-18 03:01
I agree.  It currently defaults to 40 min, which we felt was a good compromise between carb response to a low (should start to see after ~20 min) and insulin response to a correction bolus (should start to see after ~40 min).

**Comment by rnpenguin** [comment] 2014-03-18 07:57
This could be done in the code or would you want a prompt that allows you to specify number of minutes in multiples of 10 minutes intervals to an acceptable max?  If the latter, I would probably default it to the code value if no response was given after a specified amount of time in order to avoid a blocking issue.  What do you think?

**Comment by TC2013** [comment] 2014-03-18 13:21
I think what you may be asking or thinking through is whether it should be like Dexcom which uses static values for silencing alerts (different for highs/low) or if a prompt should be given at every alert. I believe the prompt at the time of the alert would be perfect using the multiples of 10 just as you suggest.

**Comment by rnpenguin** [comment] 2014-03-20 07:33
Duplicate of #9

**Closed as completed by rnpenguin** 2014-03-20 07:33 UTC
Labels: duplicate
